---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: "${K8S_PROJECT_NAME}-be"
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - git:
              repoURL: "${GH_DEV_URL}"
              revision: main
              directories:
                - path: cluster/cluster-01/*
                - path: cluster/cluster-02/*
          - list:
              elements:
                - name: dev
                  cluster: cluster-01
                  server: "${K8S_CLUSTER_MGMT}"
                - name: staging
                  cluster: cluster-01
                  server: "${K8S_CLUSTER_MGMT}"
                - name: prod-hcm
                  cluster: cluster-02
                  server: "${K8S_CLUSTER_RS}"
                - name: prod-hni
                  cluster: cluster-02
                  server: "${K8S_CLUSTER_RS}"
  template:
    metadata:
      name: "${K8S_PROJECT_NAME}-{{.name}}-be"
      annotations:
        kargo.akuity.io/authorized-stage: "${K8S_PROJECT_NAME}:{{.name}}-be"
    spec:
      project: "${K8S_PROJECT_NAME}"
      sources:
      - repoURL: "${GH_CHART_URL}"
        targetRevision: main
        path: thanh-backend-chart
        helm:
          valueFiles:
            - values-{{.name}}.yml
      destination:
        server: "{{.server}}"
        namespace: "${K8S_PROJECT_NAME}-{{.name}}-be"
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
