---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev-fe
  namespace: "${K8S_PROJECT_NAME}"
  annotations:
    kargo.akuity.io/color: violet
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: "${K8S_PROJECT_NAME}-fe"
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote-fe

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: staging-fe
  namespace: "${K8S_PROJECT_NAME}"
  annotations:
    kargo.akuity.io/color: gray
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: "${K8S_PROJECT_NAME}-fe"
    sources:
      stages:
      - dev-fe
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote-fe

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-hcm-fe
  namespace: "${K8S_PROJECT_NAME}"
  annotations:
    kargo.akuity.io/color: rose
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: "${K8S_PROJECT_NAME}-fe"
    sources:
      stages:
      - staging-fe
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote-fe

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-hni-fe
  namespace: "${K8S_PROJECT_NAME}"
  annotations:
    kargo.akuity.io/color: indigo
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: "${K8S_PROJECT_NAME}-fe"
    sources:
      stages:
      - staging-fe
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote-fe

---
apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionTask
metadata:
  name: promote-fe
  namespace: "${K8S_PROJECT_NAME}"
spec:
  vars:
  - name: gitFolder
    value: ./git-repo

  - name: chartFolder
    value: ./chart-repo

  - name: branch
    value: main

  - name: STAGE_PATH
    value: >-
      ${{ 
        ctx.stage == "dev-fe"       ? "cluster/cluster-01/dev" : 
        ctx.stage == "staging-fe"   ? "cluster/cluster-01/staging" : 
        ctx.stage == "prod-hcm-fe"  ? "cluster/cluster-02/prod-hcm" : 
        ctx.stage == "prod-hni-fe"  ? "cluster/cluster-02/prod-hni" : 
        "unknown-stage" 
      }}

  - name: CHART_VALUES_PATH
    value: >-
      ${{ 
        ctx.stage == "dev-fe"       ? "values-dev.yml" : 
        ctx.stage == "staging-fe"   ? "values-staging.yml" : 
        ctx.stage == "prod-hcm-fe"  ? "values-prod-hcm.yml" : 
        ctx.stage == "prod-hni-fe"  ? "values-prod-hni.yml" :
        "unknown-stage" 
      }}

  steps:
  - uses: git-clone
    config:
      repoURL: "${GH_DEV_URL}"
      checkout:
      - branch: main
        path: ${{ vars.gitFolder }}

  - uses: git-clone
    config:
      repoURL: "${GH_CHART_URL}"
      checkout:
      - branch: main
        path: ${{ vars.chartFolder }}

  - uses: yaml-update
    as: update-values-git
    config:
      path: ${{ vars.gitFolder }}/${{ vars.STAGE_PATH }}/values-frontend.yml
      updates:
      - key: image.tag
        value: ${{ imageFrom("${PRIVATE_REGISTRY_FE}").Tag }}
      - key: image.pullPolicy
        value: IfNotPresent

  - uses: copy
    config:
      inPath: ${{ vars.gitFolder }}/${{ vars.STAGE_PATH }}/values-frontend.yml
      outPath: ${{ vars.chartFolder }}/thanh-frontend-chart/${{ vars.CHART_VALUES_PATH }}

  - uses: git-commit
    as: commit-git-repo
    config:
      path: ${{ vars.gitFolder }}
      message: "Update Helm values for ${{ ctx.stage }}"

  - uses: git-push
    as: push-git-repo
    config:
      path: ${{ vars.gitFolder }}
      targetBranch: main

  - uses: git-commit
    as: commit-chart-repo
    config:
      path: ${{ vars.chartFolder }}
      message: "Sync Helm values with backend application repository"

  - uses: git-push
    as: push-chart-repo
    config:
      path: ${{ vars.chartFolder }}
      targetBranch: main

  - uses: argocd-update
    as: update-chart-repo
    config:
      apps:
      - name: "${K8S_PROJECT_NAME}-${{ ctx.stage }}"
        sources:
        - repoURL: "${GH_CHART_URL}"

  - uses: argocd-update
    as: update-git-repo
    config:
      apps:
      - name: "${K8S_PROJECT_NAME}-${{ ctx.stage }}"
        sources:
        - repoURL: "${GH_DEV_URL}"
