---
apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: "${K8S_PROJECT_NAME}"
  annotations:
    argocd.argoproj.io/sync-wave: "-1"

---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: git-creds
  namespace: "${K8S_PROJECT_NAME}"
  labels:
    kargo.akuity.io/cred-type: git
stringData:
  repoURL: "${GH_DEV_URL}"
  username: "${GH_USER}"
  password: "${GH_TOKEN}"

---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: chart-creds
  namespace: "${K8S_PROJECT_NAME}"
  labels:
    kargo.akuity.io/cred-type: git
stringData:
  repoURL: "${GH_CHART_URL}"
  username: "${GH_USER}"
  password: "${GH_TOKEN}"

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: "${K8S_PROJECT_NAME}-be"
  namespace: "${K8S_PROJECT_NAME}"
  annotations:
    kargo.akuity.io/color: cyan
spec:
  subscriptions:
    - image:
        repoURL: ${PRIVATE_REGISTRY_BE}
        imageSelectionStrategy: SemVer
        semverConstraint: "*.*.0"
        discoveryLimit: 10
        strictSemvers: true

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: "${K8S_PROJECT_NAME}-fe"
  namespace: "${K8S_PROJECT_NAME}"
  annotations:
    kargo.akuity.io/color: sky
spec:
  subscriptions:       
    - image:
        repoURL: ${PRIVATE_REGISTRY_FE}
        imageSelectionStrategy: SemVer
        semverConstraint: "*.*.0"
        discoveryLimit: 10
        strictSemvers: true
